site_name: Django Meilisearch
repo_url: https://github.com/Lucashcr/django_meilisearch

theme:
  name: material  # Tema (recomendo o Material for MkDocs)
  palette:
    - scheme: slate
#  logo: images/logo.png  # Opcional, seu logotipo

nav:
  - Home: 01.index.md
  - Installation: 02.installation.md
  - Configuration: 03.configuration.md
  - Basic Usage: 04.basic_usage.md
  - Advenced Features: 05.advanced_features.md
  - Contributing: 06.contributing.md
  - License: 07.license.md

# markdown_extensions:
#   - toc
#   - tables
#   - admonition  # Para notas, avisos, etc.
#   - codehilite  # Realce de sintaxe em blocos de código
#   - pymdownx.superfences  # Suporte para múltiplos blocos de código
#   - pymdownx.tabbed  # Abas para organizar conteúdo

# extra_css:
#   - css/custom.css  # Arquivo de CSS customizado (opcional)

# extra_javascript:
#   - js/custom.js  # Arquivo de JS customizado (opcional)
